apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spark-operator

resources:
  - spark-operator-rbac.yaml
  - spark-operator.yaml

configMapGenerator:
- name: sparkoperator-config
  env: sparkoperator-config.properties


configurations:
- sparkoperator-config.yaml